### ISSUE TITLE
Bit algorithms are already in Boost.Core

### ISSUE THREAD

**Issue by glenfe** [JeffGarland/liaw2022#2]
>c++20 bit operations (header <bit>)
>
>    rotate: rotl, rotr
>    counting: countl_zero, countr_one, popcount

See:

- https://github.com/boostorg/core/blob/develop/include/boost/core/bit.hpp
- https://www.boost.org/doc/libs/1_79_0/libs/core/doc/html/core/bit.html
- https://github.com/boostorg/algorithm/pull/92#issuecomment-1119035307

**Comment by JeffGarland** [comment]
Yes thanks -- we did realize that later.  However, we've done some things that may be improvements -- I expect the pull request will come for core.

**Comment by glenfe** [comment]
Improvements to Core are always welcome :)
